allprojects {
    buildscript {
        configurations.all {
            resolutionStrategy {
                eachPlugin {
                    if (requested.id.id == 'com.android.application') {
                        useVersion '9.0.1'
                    }
                    if (requested.id.id == 'com.android.library') {
                        useVersion '9.0.1'
                    }
                }
            }
        }
    }
}

settingsEvaluated { settings ->
    settings.pluginManagement {
        plugins {
            'com.android.application' version '9.0.1'
            'com.android.library' version '9.0.1'
        }
        resolutionStrategy {
            eachPlugin {
                if (requested.id.id == 'com.android.application') {
                    useVersion '9.0.1'
                }
                if (requested.id.id == 'com.android.library') {
                    useVersion '9.0.1'
                }
            }
        }
    }
}
